# Generated by Django 5.2.3 on 2025-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
