# Generated by Django 5.2.3 on 2025-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
